name: hack_to_machine_assmebler
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.15.0 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  build_runner: ^2.1.2
  pedantic: ^1.10.0
  test: ^1.17.12
  injectable_generator: ^1.5.0
dependencies:
  args: ^2.3.0
  dartz: ^0.10.1
  freezed: ^0.14.5
  get_it: ^7.2.0
  injectable: ^1.5.0
  mockito: ^5.0.17
